# Site settings
name: 气象小哥
email: 1151651460@qq.com
author: Luming
url: 
resume_site: 
github: https://github.com/khtkjeg/
baseurl: 
description: Actually, less is more!
meta_description: 路明;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: 我为码农，为自己而活
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: khtkjeg
#highlighter: Pygments
highlighter: rouge

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : yungentie
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light